
; build web version

(rule
 (alias web)
 (action (copy main/hipjs.bc.js hipjs.bc.js)))
(rule
 (alias web)
 (action (copy web/main.js main.js)))

(rule
 (alias web)
 (target coi-serviceworker.min.js)
 (action (run curl -sOL https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.min.js)))

(rule
 (alias web)
 (target index.html)
 (deps (source_tree test/examples) (source_tree test/evaluation) web/index.html coi-serviceworker.min.js hipjs.bc.js bundle.js z3-built.js z3-built.wasm ace_ocaml.js page.js)
 (action (run web/examples.sh web/index.html index.html)))

(rule
 (alias web)
 (targets z3-built.js z3-built.wasm)
 (deps (source_tree node_modules))
 (action (progn
  (run cp node_modules/z3-solver/build/z3-built.wasm z3-built.wasm)
  (run cp node_modules/z3-solver/build/z3-built.js z3-built.js))))

(rule
 (alias web)
 (targets bundle.js)
 (deps main.js (source_tree node_modules))
 (action (bash "node node_modules/browserify/bin/cmd.js main.js -o bundle.js --standalone z3")))

(rule
 (alias web)
 (action (copy web/page.js page.js)))
(rule
 (alias web)
 (action (copy web/ace_ocaml.js ace_ocaml.js)))

(rule
 (alias web)
 (targets (dir deploy))
 (deps coi-serviceworker.min.js hipjs.bc.js bundle.js index.html z3-built.js z3-built.wasm ace_ocaml.js page.js)
 (action (progn
  (run mkdir deploy)
  (run cp %{deps} %{targets}))))
